### ISSUE TITLE
Fake messages on multiplayerpiano.com

### ISSUE THREAD

**Issue by AlexApps99** [ledlamp/mpp.terrium.net#4]
> Server:multiplayerpiano.com will be permanently shut down in 3 days so please evacuate to mpp.terrium.net

Why? This hardly seems like the official replacement...

If I didn't know better I would think that somebody set their username to "Server"
 just to trick users into using a crummy mirror...

But you wouldn't do that... Would you?

**Comment by ledlamp** [comment]
the "[multiplayer piano] will be shut down [soon]" thing has been said a lot for a while now, it means nothing. I think it's usually blobek saying that. Unless the message is white and the author does not appear in the room, has the id "00000..." or is in any other way impossible to be a normal user, it's meaningless. Now if it is... then it must be brandon, but he could be joking too (he's weird like the rest), although it would be very interesting if he actually referenced mpp.terrium.net 🤔

**Comment by Stitch-Lizzys-BF-from-join-my-zoom** [comment]
What happened to MPP and why won't it load?
I'm the owner of the room "join my zoom"(the only one with a bouncer) and im kinda sad i can't get on cause that's where me and my friends talk sometimes and where i was starting to learn how to code and play piano. I would get on MPPClone, but it is blocked for me due to the school blocking it.
So yeah did it get shut down or something?

**Comment by Stitch-Lizzys-BF-from-join-my-zoom** [comment]
Yeah so i just found out it got blocked so yeah now im really sad
